services:
  node:
    container_name: node
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - compose-net
    volumes:
      - ./node:/usr/src/app
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      MYSQL_PASSWORD: root
    networks:
      - compose-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql/schema:/var/lib/mysql
      - ./mysql/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - node
    networks:
      - compose-net
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf

networks:
  compose-net:
    driver: bridge
